export const CASE_GET_PERFUMES = "GET_PERFUMES";
export const CASE_GET_ONE_PERFUME = "GET_ONE_PERFUME";

export const CASE_GET_BRANDS = 'GET_BRANDS';

export const CASE_GET_CART = "GET_CART";

export const CASE_GET_FAVORITE = "GET_FAVORITE";